name: BUILD ALPINE

on:
  push:
    paths:
      - '!README.md'
      - '**/**'
  pull_request:
    paths:
      - '!README.md'
      - '**/**'
  workflow_dispatch:

env:
  # This file must ends with .patch
  PATCH_FILE_NAME: "0001.patch"

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Prepare git dir
        run: |
          mkdir -p src

      - name: Checkout Revision src
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: "${{ secrets.REVISION_REPO }}"
          ref: "${{ secrets.REVISION_BRANCH }}"
          token: ${{ secrets.MY_TOKEN }}
          path: src

      - name: Set environment variable
        working-directory: src
        run: |
          git fetch --tags origin

          # echo $(git describe --tags --match deluge-[0-9]*)
          echo $(git describe --tags --match deluge-[0-9]*)
          export VERSION=$(python3 version.py)
          echo $VERSION
          if [[ $VERSION == *"dev"* ]]; then
            echo "$VERSION is not a release version, terminating GitHub Action."
            exit 1
          else
            BASED_ON_TAG_VERSION=${VERSION:0:5}
          fi

          echo "BASED_ON_TAG_VERSION=$BASED_ON_TAG_VERSION" >> $GITHUB_ENV

          # Use this to generate release tag
          BUILD_VERSION=$(jq -r '.version' ../build.json)
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV

          # Generate Patch
          git diff deluge-$BASED_ON_TAG_VERSION -- . ":(exclude).github" ":(exclude)README.md" > ../alpine/${{ env.PATCH_FILE_NAME }}

      - name: Build alpine deluge
        run : |

          # build Docker base image
          docker build --target=alpine-builder .
          docker build --target=alpine-apk-builder --tag="bulild:alpine-apk-builder" --build-arg VERSION=${{ env.BASED_ON_TAG_VERSION }} --build-arg PATCH=${{ env.PATCH_FILE_NAME }} .

          CONTAINER_ID="$(docker create "bulild:alpine-apk-builder")"
          docker cp "${CONTAINER_ID}:/pkgs/" .
          docker rm "${CONTAINER_ID}"

          rm -rf pkgs/apk/x86_64/APKINDEX*
          ls -l pkgs/apk/x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: alpine-packages
          path: pkgs/apk/x86_64

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        if: github.ref == 'refs/heads/main'
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.BUILD_VERSION }}
          title: deluge-${{ env.BASED_ON_TAG_VERSION }} alpine/edge x86_64
          files: |
            pkgs/apk/x86_64/*

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        if: github.ref == 'refs/heads/main'
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/docker-deluge
          registry: ${{ secrets.DOCKER_REGISTRY }}
          tags: ${{ env.BUILD_VERSION }}, latest
          dockerfile: Dockerfile-deluge
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
